---

- name: "Make kubelet static pods dir"
  file:
    path: "{{ kubelet_config_dir }}/manifests"
    state: directory
    mode: 0755

- name: "Create kubelet config file"
  template:
    src: kubelet-config.yml.j2
    dest: "{{ kubelet_config_dir }}/kubelet-config.yml"

- name: "Run kubelet"
  command: >
    docker run
    --restart=on-failure:5
    --net=host
    --pid=host
    --name {{ kubelet_container_name }}
    --privileged
    -v /dev:/dev
    -v /etc/resolv.conf:/etc/resolv.conf 
    -v /etc/os-release:/etc/os-release:ro
    -v /etc/cni:/etc/cni:ro
    -v /opt/cni:/opt/cni:ro
    -v /var/run:/var/run
    -v /var/log:/var/log
    -v /var/lib/docker:/var/lib/docker:rw
    -v {{ kubelet_config_dir }}:/etc/kubernetes
    -d
    hyperkube:{{ hyperkube_version }} kubelet
    --api-servers=https://{{ api_ip }}:{{ api_ssl_port }}
    --kubeconfig=/etc/kubernetes/kubelet-config.yml
    --allow-privileged=true
    --pod-manifest-path=/etc/kubernetes/manifests
    --pod-infra-container-image=pause-amd64:{{ pause_version }}
    --cgroups-per-qos=false
    --enforce-node-allocatable=""
    --network-plugin=cni
