kubelet_config_dir: "/tmp/k8s"

etcd_version: v3.2.0-rc.0
hyperkube_version: v1.6.4
pause_version: 3.0

kubelet_container_name: kubelet

api_ip: 192.168.99.100
api_port: 8080
api_ssl_port: 8443

etcd_ip: 192.168.99.100
etcd_peer_port: 2380
etcd_port: 2379

service_cluster_cidr: 10.10.0.0/24
cluster_cidr: 10.20.0.0/16

cluster_dns: 10.10.0.10