kubelet_config_dir: "/opt/k8s"

kubelet_container_name: kubelet

api_ip: 127.0.0.1
api_port: 8080
api_ssl_port: 8443

etcd_ip: 127.0.0.1
etcd_peer_port: 2380
etcd_port: 2379

service_cluster_cidr: 10.10.0.0/24
cluster_cidr: 10.20.0.0/16

cluster_dns: 10.10.0.10
